backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads


collections:
  - name: "about"
    folder: "about"
    create: false
    delete: false
    fields:
      - name: "test-id"
        label: "Test ID"
        widget: "string"
        default: "this is a test"
        required: true
