backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads


collections:
  - name: "about"
    label: "About"
    file: "source/_data/about.yml"
    format: yml
    fields:
      - {label: "Page Header", name: "page-header", widget: "string"}
      - label: Sections
        name: section
        widget: list
        fields:
          - {label: "Section Header", name: "section-header", widget: "string"}
          - {label: "Section Text", name: "section-text", widget: "markdown"}
          - {labedl: "Section Image", name" "section-image", widget: "image"}
