backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads


collections:
  - label: "Pages"
    name: "pages"
    files:
    - name: "about"
      label: "About"
      file: "source/_data/about.yml"
      format: yml
      fields:
        - {label: "Page Header", name: "page-header", widget: "string"}
        - label: Sections
          name: sections
          widget: list
          fields:
            - {label: "Section Header", name: "header", widget: "string"}
            - {label: "Section Text", name: "text", widget: "markdown"}
            - label: "Section Image"
              name: "image"
              widget: "list"
              fields:
              - {label: "Image", name: "src", widget: "image"}
              - {label: "Alt Text", name: "alt", widget: "string"}
